"use client"
import DesktopNav from "@/components/Nav/DesktopNav"
import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import Mobilenav from "@/components/Nav/Mobilenav"
import Footer from "@/components/Footer/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "app",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' key={window?.location.href}>
      <body className={inter.className}>
        {!window.location.pathname.includes('auth')? <DesktopNav />:null}
        {/* <Mobilenav /> */}
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  )
}
